# Generated by Django 4.2.4 on 2023-08-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='profession',
            new_name='profession_id',
        ),
    ]
