# Generated by Django 4.2.4 on 2023-08-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='branch',
            new_name='branch_id',
        ),
    ]
